#include "help.hpp"

const QString code(const QString str) {
    const QString codeRepl = "<span style='"
        "background-color:" "grey;"
        "font-family:" "monospace;"
        "padding:" "2px;"
    "'>%1</span>";
    return codeRepl.arg(str);
}
const QString hl(const QString str) {
    const QString hlRepl = "<span style='background-color:" "#C89353;'>"
        "&nbsp;%1&nbsp;"
    "</span>";
    return hlRepl.arg(str);
}
const QString nl(const QString str) {
    const QString nlRepl = "<div style='"
        "display:" "inline-block;"
        "margin-left:" "20px;"
    "'>%1</div>";
    return nlRepl.arg(str);
}
const QString qu = "<span style='background-color:" "#AAAAAA;'>&nbsp;</span>&nbsp;";

const QString APP_HELP = 
"<h1><b>IMPORTANT THINGS</b></h1>"
    "<ul>"
        "<li>"
            "<p>Decks starting with a "+hl(".")+" are temporary and will be <i>put in the recycle bin</i> next app startup (or on request, see the home screen's help)</p>"
            "<p>Removing the "+hl(".")+" at the start of a deck name will make it not temporary anymore, and adding one will make it temporary."
        "</li>"
        "<li>"
            "<p>Note features cannot be nested within itself, as it will see the close of the inner feat and not look further for the close to the outer one.</p>"
            "<p>For example, this "+code("||hi | [[bye1::bye2]]||")+" is ok because they are different but this "+code("[[bye1||[[front::back]]||bye3]]")+" is not ok.</p>"
            "<p>See "+hl("Tricks")+" below for some workarounds, or come up with your own, or make an extension if you care enough &lt;3</p>"
        "</li>"
    "</ul>"
"<h1>How the app works</h1>"
    "<p>This app is a flashcard app where you complete flashcards in order to grow a tree.</p>"
    "<p>You'll get it as you go along, but if not you can always check the help for specifc places by the <b>Help &gt; This screen</b> menu.</p>"
"<h2>Keybinds</h2>"
    "<p>These work in any scene, as long as you aren't selecting an editable element</p>"
    "<ul>"
        "<li>H or &lt;Escape&gt; to go home</li>"
        "<li>B to browse cards</li>"
        "<li>G to play the game</li>"
        "<li>P to manage plugins</li>"
    "</ul>"
"<h1>FAQ</h1>"
    "<ul>"
        "<li><b>Did it save my changes?</b>"
            +nl("Yes. Every time you change even one letter it saves to the file. This includes renaming."
            )+"</li>"
        "<li><b>How do I find the logs/config directory?</b>"
            +nl("To see the logs: <b>Help &gt; Logs</b>. Config directory is the first log on the list."
            )+"</li>"
    "</ul>"
"<h1>Tricks</h1>"
    "<p>If you are using this often consider making note templates to do these</p>"
    "<ul>"
        "<li>"
            "<h3>Random hidden per side</h3>"
            "<p>With the hidden feature, the randomness overrides the per-side.</p>"
            "<p>To get around this, you can do something like this: "+code("[[front1::||front2::]][[::back]]")+"."
                +nl("2 hidden features are used, where one randomly picks one of the fronts to use and the other only appears on the back."
                )+"</p>"
        "</li>"
    "</ul>"
;

const QString HOME_HELP = 
"<h2>Menu items</h2>"
    "<ul>"
        "<li><b>File</b><ul>"
            "<li>Delete all temporary decks (starting with "+hl(".")+") (moves them to the recycle bin if possible)</li>"
        "</ul></li>"
    "</ul>"
"<h2>Decks</h2>"
    "<h3>Basic deck stuff</h3>"
        "<p>Use the first field to select a deck. You can type in the box and it will give suggestions or you can use the dropdown to select a deck.</p>"
        "<p>Whatever's present there is the deck you are currently using.</p>"
        "<p>The rename box below allows you to rename the deck. Just edit the box and it should work!</p>"
        "<p><i>If the rename text is red, blank or not matching up with the deck selector dropdown then the name is invalid.</i> There may be an existing deck with that name or another problem.</p>"
    "<h3>Making new decks</h3>"
        "<p>To make a new deck, first use the deck selector to select the empty deck (the one with no name). Then, rename the deck and voila! A new deck is born.</p>"
    "<h3>Deleting decks</h3>"
        "<p>To delete a deck, backspace the name in the <i>rename deck field</i> then press backspace one more time to give an "+hl("are you sure?")+" dialog.</p>"
        "<p>Or, you can use the delete button in the deck options popup.</p>"
        "<p>OR, you can prefix the deck with "+hl(".")+" and it will be deleted next app reset or on demand through the menu item.</p>"
    "<h3>Deck options (for the current deck)</h3>"
        "<ul>"
            "<li>Delete the deck (does the same thing as backspacing the name, except does not ask for verification first)</li>"
            "<li>Copy the deck with some requirements, e.g. to make it temporary</li>"
        "</ul>"
;

const QString BROWSE_HELP = 
"<h2>Keybinds</h2>"
    "<ul>"
        "<li>&lt;Ctrl+Shift+Delete&gt; to delete currently selected item</li>"
        "<li>&lt;Ctrl+Shift+Enter&gt; to make a new note</li>"
        "<li>&lt;Esc&gt; to go back</li>"
    "</ul>"
"<h2>Menu items</h2>"
    "<ul>"
        "<li><b>File</b><ul>"
            "<li>Options for deleting/resetting notes</li>"
            "<li>New note/delete current note (with keybind)</li>"
        "</ul></li>"
        "<li><b>Help</b><ul>"
            "<li>Note feature help screen - <b>very helpful!</b> The features are only described there, please look there for help.</li>"
        "</ul></li>"
    "</ul>"
"<h2>Tree column headers</h2>"
    "<p>You can click on any header to sort by it, and click again to sort the other direction. "
        "You can also resize the headers!</p>"
    "<ul>"
        "<li><i>Name</i> - the name of the note (a one-line representation of the note's contents)</li>"
        "<li>📚 - <b>Cards</b> (The amount of cards produced by the note)</li>"
        "<li>‼️ - <b>Errors</b> (The amount of errors in the note)</li>"
        "<li>📝 - <b>Templates</b> (The amount of templates specified by the note)</li>"
        "<li>🏷️ - <b>Tags</b> (The list of tags provided)</li>"
    "</ul>"
"<h2>Notes and cards</h2>"
    "<p><i>Notes</i> are blocks of information and <i>cards</i> are a way to view that information.</p>"
    "<p>Cards are created when specific features are added to cards.</p>"
    "<p>For example, you can split your note into a front and a back side with <b>---</b> to separate it into a front and back side</p>"
    "<p>There are some sample cards for you to look at for help.</p>"
"<h2>Markdown support</h2>"
    "<p>This app contains various ways to markup your text;</p>"
    "<ul>"
        "<li><i>*italics*</i></li>"
        "<li><b>**bold**</b></li>"
        "<li><u>_underline_</u></li>"
        "<li><s>~~strikethrough~~</s></li>"
        "<li>Bullet points: Can use one of these characters for different bullet symbols: * - +</li>"
        "<li>"+hl("==highlight==")+"</li>"
        "<li>"+code("`code`")+"</li>"
    "</ul>"
"<h2>Escaping</h2>"
    "<p>Sometimes you may want to use things in your notes literally (e.g. "+code("---")+") without it being recognised as a note feature or whatever. "
        "For that, we have backslashes!</p>"
    "<p>All backslashes will be removed from the final text, but you can use this to your advantage. "
        "Using backslashes in places e.g. "+code("\\---")+" or "+code("-\\--")+" will make the feature not parse as a feature!</p>"
    "<p>Rules for backslashes: place it wherever it works (try on the inside or the left of features)</p>"
    "<h3>Additional uses for backslash</h3>"
    "<ul>"
        "<li>To get a regular backslash in your text you can escape the backslash itself; i.e. "+code("\\\\")+"</li>"
        "<li>You can also backslash and then have a newline to remove the newline in the final note, useful if you want to break a complex statement/expression for one line into multiple.</li>"
        "<li>If you write "+code("\\n")+" then it will insert a newline there. Useful if you want to write multiple lines in one (but pls don't)</li>"
    "</ul>"
    "<p><b>HINT</b>: (hopefully) if you are escaping a feature it will not have its colour, and that can be used to see if it worked.</p>"
"<h2>Scheduling</h2>"
    "<p>Scheduling for cards is auto generated and updated at the bottom of the file.</p>"
    "<p>Adding text after it will still work, but the text will get moved before it when the card is next completed.</p>"
    "<p>The scheduling info is different for different card features, so copying it to another card may/may not work.</p>"
    "<p>To reset scheduling you can just delete the line. It will get recreated later, but with a new schedule.</p>"
"<h2>How to use</h2>"
    "<p>You can select notes on the left and edit their contents on the right</p>"
    "<p>There is a bar in the middle you can move left/right to adjust the screen to your needs</p>"
    "<p>Press the "+hl("New note")+" button in the title to make a new note</p>"
    "<p>Notes can contain things in them that create cards or that affect the text."
        +nl("By default, notes create 0 cards so don't expect them to do stuff unless you add things to them"
        )+"</p>"
    "<p>Things you can add to your notes are in a layout above the note."
        +nl(
        "Pressing the arrow expands/contracts to see extra."
        "<br>Pressing the settings button allows you to see all of them at once, and clicking on each will reveal details and help for if you are unsure of what they do."
        )+"</p>"
    "<p>Below the note input there is a preview. Click on the preview to change side (front vs back) and use the arrows to select between different cards generated by that note."
        +nl("The preview will display errors that are present in the note too."
        )+"</p>"
"<h2>Note templates</h2>"
    "<p>Note templates are used in 2 phases - defining them, then using them.</p>"
    "<p>There are some examples of note template uses in the example cards</p>"
    "<h3>Structure</h3>"
        "<p>Note templates are comprised of a header and contents, and are contained in "+code("|| ... ||")+" for usage (or "+code("|! ... ||")+" for one char usage) or "+code("|= ... =|")+" for definitions (or "+code("|: ... :|")+" for local definitions).</p>"
        "<p>The header is separated from the body of the template via a "+code(":")+" or a "+code("|")+" or a space or a newline <i>unless you use a one char usage (see below)</i>.</p>"
        "<p>After the header is an optional argument specification. This is contained within "+code("[]")+" and is separated from the body in the exact same way as the header. See below for more info about arguments."
            +nl(
            "Here are example structures: "+code("|| name [stuff here] conts ||")+"  "+code("|!- [stuff here]: conts ||")
            )+"</p>"
        "<p>The body for template usages is split up into multiple arguments, which are separated by a "+code("|")+" only.</p>"
        "<p>Please do not put note template things inside other note template things. Nesting is not supported.</p>"
        "<p><b>Unlike other features</b>, this will not keep spacing in between arguments (so it still will before and after)."
            +nl(
            "That means that this: "+code("|= hi : bye =|")+" is the same as this: "+code("|=hi:bye=|")+"."
            "<br>The spacing is <i>only</i> stripped at the start/end of the header, contents or between arguments (e.g. "+code("|| hi | arg1 | arg2 ||")+" -> "+code("||hi|arg1|arg2||")+")"
            )+"</p>"
        "<p><i>To use a note template, use the same header as the definition.</i></p>"
        "<p><b>The note template usage with "+code("|!")+" is special and does not follow the rules above.</b> Instead if having "+code("|| name args ||")+" the first character after "+code("!")+" is the name."
            +nl(
            "For example, if a note template had the name "+code("-")+" then a usage that would work is "+code("|!-args||")+"."
            "<br>Another example for understanding: If the note template was named "+code("!")+" Then it could be used like this: "+code("|!! args ||")+" (as stated above, there can be extra spaces. But keep in mind if you have "+code("|! ! arg ||")+" it will use the note template with name "+code(" ")+"!)"
            "<br>You can skip the extra gap between the title and the contents here, e.g. "+code("|!-contents||")+
            "<br><i>Please remember for these that the name must be one character long</i>"
            )+"</p>"
        "<p>"+qu+"Multiple note templates of the same type (global&global or local&local) cannot have the same name, but if a local note template has the same name as a global one the local one will be used instead.</p>"
    "<h3>Arguments</h3>"
        "<p>Arguments are used in note template definitions by a % then the name then either another % or a space.</p>"
        "<p>Arguments are specified as either %index (e.g. "+code("%1")+" for the first argument) or %name (when defined in an argument specifier) or "+code("%#")+" (for every argument separated by "+code("|")+").</p>"
        "<p>The argument specifier is a space separated list of argument names which match up to their indexes.</p>"
        "<p>For more info on or methods for utilising arguments, see the <b>Help &gt; Argument Help</b> menu.</p>"
;

const QString ARGUMENT_HELP =
"<h1>Arguments quick reference</h1>"
    "<p>Arguments are used in note template definitions by a % then the name then either another % or a space.</p>"
    "<p><i>Argument names must only contain letters and numbers</i> (except you can have arguments called "+code("-")+" which will skip that argument)</p>"
"<h2><u>Argument specifier</u></h2>"
    "<p>The argument specifier is in between the template name and contents, and is contained within "+code("[]")+"."
        +nl("It is separated from both by either a "+code(":")+" or a "+code("|")+" or a space or a newline."
       )+"</p>"
    "<p>Inside the brackets is a space separated list of names. The arguments will be named by this in the order they are passed in.</p>"
    "<p>The argument name in the argument specifier can have suffixes like regular argument usage, for example "+code("[name|default]")+"</p>"
    "<p>You can also specify the same argument to have multiple names with /, e.g. "+code("[name1/name2]")+"</p>"
    "<p>Additionally, using "+code("name=thing")+" allows you to set macros (and unless / is used it will not take up an argument; i.e. "+code("[macro=this first second]")+")"
        +nl(
        "Macros are substituted in-place. You can also use % in your macros, but there is a recursion limit."
        "<br>For example, "+code("|: test [name=Hello,\\ %1] Remember to say '%name' :|")+" applied via "+code("||test me||")+" will output "+hl("Remember to say 'Hello, me'")
        )+"</p>"
    "<h3>Argument specifier options (suffixes)</h3>"
    "<ul>"
        "<li>"+code("|def")+" - if the output is null (e.g. no argument was provided), display the text after instead.</li>"
    "</ul>"
"<h2><u>Argument usage</u></h2>"
    "<p>Arguments are specified as either %index (e.g. "+code("%1")+" for the first argument) or %name (when defined in an argument specifier) or "+code("%#")+" (for every argument separated by "+code("|")+").</p>"
    "<p>Arguments must end with either a space (in which case the space is kept) or a %</p>"
    "<p>%index arguments can be negative, e.g. "+code("%-1")+" which would give the last argument. Also, "+code("%0")+" is equivalent to "+code("%#")+" for convenience</p>"
    "<p>Arguments can be used with prefixes and/or suffixes, for example "+code("%.name")+", "+code("%name[1")+" or "+code("%.name[0")+".</p>"
    "<p>They can be stacked and will be executed in the order you put them in, so e.g. "+code(".^")+" would first lower <i>then</i> title case, converting e.g. "+hl("hElLo wOrLd!")+" to "+hl("Hello World!")+".</p>"
    "<h3>Argument prefixes</h3>"
    "<ul>"
        "<li>"+code(".")+" - converts text to lower case</li>"
        "<li>"+code("*")+" - converts text to UPPER CASE</li>"
        "<li>"+code("^")+" - converts text to Title Case (<i>other letters will not be touched</i>)</li>"
        "<li>"+code("\"")+" - converts text to Sentence case (<i>other letters will not be touched</i>)</li>"
    "</ul>"
    "<h3>Argument suffixes</h3>"
    "<ul>"
        "<li>"+code("[idx")+" - get the <idx>th char of the input (can be negative to get the last characters instead of the first)</li>"
        "<li>"+code("[start:stop")+" - get the <start>th to <stop>th chars of the input (can both also be negative)"
            "<br><i>Additionally</i>, the numbers can be left blank. If they are, it will go from the start or until the end depending on which was blank.</li>"
        "<li>"+code("[start:stop:step")+" - Same as above start:stop, except only displays every stepth char between the range."
            "<br><i>The step can be negative to reverse the text.</i></li>"
        "<li>"+code("{idx")+" or "+code("{start:stop")+" or "+code("{start:stop:step")+" - same as above, but for words instead of characters."
        "<li>"+code("|def")+" - if the output is currently null (e.g. no argument or you indexed out of bounds), display the text after instead."
            "<br>Overrides the one set for the variable as a whole if used at the start of the suffix.</li>"
        "<li>"+code(";sep")+" - splits the text by 'sep' (converts all sep characters to spaces so you can use "+code("{")+" to index)"
            "<br><b>NOTE<b>: It replaces all existing spaces with a special character that gets replaced with a space at the end to make everything work. "
            "But don't worry, you can still split by a space (remember to escape it tho)</li>"
        "<li>"+code("=sep")+" - joins the text with 'sep' (replaces all spacing)"
    "</ul>"
;

const QString PLUGVIEW_HELP = 
"<p>Select plugins to view information about them and disable them.</p>"
"<p>Plugin descriptions will only show for enabled plugins.</p>"
"<p>Press the <b>Load plugin</b> menu item to load one or more plugins from your hard drive."
    "This gives you the option to move them or to copy them (move gets rid of the original file, copy keeps the original).</p>"
"<h2>Status types</h2>"
    "<ul>"
        "<li>🤎 - the plugin is disabled</li>"
        "<li>💔 - the plugin failed to load</li>"
        "<li>💖 - the plugin loaded successfully!</li>"
    "</ul>"
;

const QString GAME_HELP =
"<p>Click while hovering over a card to flip (can press again to unflip), and once flipped press a button or key on your keyboard as listed on the right to finish and reschedule the card.</p>"
"<p>Reset and Skip both don't change the score of the card but just reschedule it for later (skip a lot longer away than reset)</p>"
"<p>The times present are only an aim. The app gives you cards sorted based on these times, so when you will recieve these cards is independent of the times.</p>"
"<h2>Keybinds</h2>"
    "<ul>"
        "<li>&lt;Esc&gt; to go back to the home screen</li>"
        "<li>All the keys shown on the buttons that show when you press on a card. The numbers/symbols in bold aren't just for pretty you know</li>"
    "</ul>"
"<h2>Menu items</h2>"
    "<ul>"
        "<li><b>File</b><ul>"
            "<li>Reset current set of cards you're looking at. This will mean you get a whole new set of cards (tho the card you're looking at will stay)</li>"
        "</ul></li>"
    "</ul>"
;

