#pragma once
#include <QString>

const QString APP_HELP = 
"<h1><b>IMPORTANT THINGS</b></h1>"
    "<ul>"
        "<li>"
            "<p>Decks starting with a '.' are temporary and will be <i>put in the recycle bin</i> next app startup (or on request, see the home screen's help)</p>"
            "<p>Removing the '.' at the start of a deck name will make it not temporary anymore, and adding one will make it temporary."
        "</li>"
    "</ul>"
"<h1>How the app works</h1>"
    "<p>This app is a flashcard app where you complete flashcards in order to grow a tree.</p>"
    "<p>You'll get it as you go along, but if not you can always check the help for specifc places by the <b>Help->This screen</b> menu.</p>"
"<h2>Keybinds</h2>"
    "<p>These work in any scene, as long as you aren't selecting an editable element</p>"
    "<ul>"
        "<li>&lt;H&gt; or &lt;Escape&gt; to go home</li>"
        "<li>&lt;B&gt; to browse cards</li>"
        "<li>&lt;G&gt; to play the game</li>"
        "<li>&lt;P&gt; to manage plugins</li>"
    "</ul>"
"<h1>FAQ</h1>"
    "<ul>"
        "<li><b>Did it save my changes?</b><br>"
            "Yes. Every time you change even one letter it saves to the file. This includes renaming.</li>"
        "<li><b>How do I find the logs/config directory?</b><br>"
            "To see the logs: `Help` > `Logs`. Config directory is the first log on the list.</li>"
    "</ul>"
;

const QString HOME_HELP = 
"<h2>Menu items</h2>"
    "<ul>"
        "<li><b>File</b><ul>"
            "<li>Delete all temporary decks (starting with '.') (moves them to the recycle bin if possible)</li>"
        "</ul></li>"
    "</ul>"
"<h2>Decks</h2>"
    "<h3>Basic deck stuff</h3>"
        "<p>Use the first field to select a deck. You can type in the box and it will give suggestions or you can use the dropdown to select a deck.</p>"
        "<p>Whatever's present there is the deck you are currently using.</p>"
        "<p>The rename box below allows you to rename the deck. Just edit the box and it should work!</p>"
        "<p><i>If the rename text is red, blank or not matching up with the deck selector dropdown then the name is invalid. There may be an existing deck with that name or another problem.</i></p>"
    "<h3>Making new decks</h3>"
        "<p>To make a new deck, first use the deck selector to select the empty deck (the one with no name). Then, rename the deck and voila! A new deck is born.</p>"
    "<h3>Deleting decks</h3>"
        "<p>To delete a deck, backspace the name in the <i>rename deck field</i> then press backspace one more time to give an 'are you sure?' dialog.</p>"
        "<p>Or, you can use the delete button in the deck options popup.</p>"
        "<p>OR, you can prefix the deck with '.' and it will be deleted next app reset or on demand through the menu item.</p>"
    "<h3>Deck options (for the current deck)</h3>"
        "<ul>"
            "<li>Delete the deck (does the same thing as backspacing the name, except does not ask for verification first)</li>"
            "<li>Copy the deck with some requirements, e.g. to make it temporary</li>"
        "</ul>"
;

const QString BROWSE_HELP = 
"<h2>Keybinds</h2>"
    "<ul>"
        "<li>&lt;Alt+Delete&gt; to delete currently selected item</li>"
        "<li>&lt;Alt+Enter&gt; to make a new note</li>"
        "<li>&lt;Esc&gt; to go back</li>"
    "</ul>"
"<h2>Menu items</h2>"
    "<ul>"
        "<li><b>File</b><ul>"
            "<li>Options for deleting/resetting notes</li>"
            "<li>New note/delete current note (with keybind)</li>"
        "</ul></li>"
        "<li><b>Help</b><ul>"
            "<li>Note feature help screen</li>"
        "</ul></li>"
    "</ul>"
"<h2>Tree column headers</h2>"
    "<p>You can click on any header to sort by it, and click again to sort the other direction. "
        "You can also resize the headers!</p>"
    "<ul>"
        "<li><i>Name</i> - the name of the note (a one-line representation of the note's contents)</li>"
        "<li>📚 - <b>Cards</b> (The amount of cards produced by the note)</li>"
        "<li>🚩 - <b>Priority</b> (The priority of the card, 0 being default, positives being more important)"
        "<li>‼️ - <b>Errors</b> (The amount of errors in the note)</li>"
        "<li>📝 - <b>Templates</b> (The amount of templates specified by the note)</li>"
        "<li>🏷️ - <b>Tags</b> (The list of tags provided)</li>"
    "</ul>"
"<h2>Notes and cards</h2>"
    "<p><i>Notes</i> are blocks of information and <i>cards</i> are a way to view that information.</p>"
    "<p>Cards are created when specific features are added to cards.</p>"
    "<p>For example, you can split your note into a front and a back side with <b>---</b> to separate it into a front and back side</p>"
    "<p>There are some sample cards for you to look at for help.</p>"
"<h2>Markdown support</h2>"
    "<p>This app contains various ways to markup your text;</p>"
    "<ul>"
        "<li>*<i>italics</i>*</li>"
        "<li>**<b>bold</b>**</li>"
        "<li>_<u>underline</u>_</li>"
        "<li>~~<s>strikethrough</s>~~</li>"
        "<li>Bullet points: Can use one of these characters for different bullet symbols: * - +</li>"
        "<p>Not possible to showcase the style of in this help menu, but able to use in your notes:"
        "<li>==highlight==</li>"
        "<li>`code`</li>"
    "</ul>"
"<h2>Escaping</h2>"
    "<p>Sometimes you may want to use things in your notes literally (e.g. <b>---</b>) without it being recognised as a note feature or whatever. "
        "For that, we have backslashes!</p>"
    "<p>All backslashes will be removed from the final text, but you can use this to your advantage. "
        "Using backslashes in places e.g. <b>-\\--</b> will make the feature not parse as a feature!</p>"
    "<p>To get a regular backslash in your text you can escape it; \\\\</p>"
    "<p>Rules for backslashes: place it wherever it works (usually on the <i>inside or middle</i> of features not the outside)</p>"
"<h2>Scheduling</h2>"
    "<p>Scheduling for cards is auto generated and updated at the bottom of the file.</p>"
    "<p>Adding text after it will still work, but the text will get moved before it when the card is next completed.</p>"
    "<p>The scheduling info is different for different card features, so copying it to another card may/may not work.</p>"
    "<p>To reset scheduling you can just delete the line. It will get recreated later, but with a new schedule.</p>"
"<h2>How to use</h2>"
    "<p>You can select notes on the left and edit their contents on the right</p>"
    "<p>There is a bar in the middle you can move left/right to adjust the screen to your needs</p>"
    "<p>Press the 'New note' button in the title to make a new note</p>"
    "<p>Notes can contain things in them that create cards or that affect the text."
        "By default, notes create 0 cards so don't expect them to do stuff unless you add things to them</p>"
    "<p>Things you can add to your notes are in a layout above the note. "
        "Pressing the arrow expands/contracts to see extra. "
        "Pressing the settings button allows you to see all of them at once, and clicking on each will reveal details and help for if you are unsure of what they do.</p>"
    "<p>Below the note input there is a preview. Click on the preview to change side (front vs back) and use the arrows to select between different cards generated by that note. "
        "The preview will display errors that are present in the note too.</p>"
"<h2>Note templates</h2>"
    "<p>Note templates are used in 2 phases - defining them, then using them.</p>"
    "<p>There are some examples of note template uses in the example cards</p>"
    "<h3>Defining note templates</h3>"
        "<p>Note templates are contained within <b>%|</b> and <b>|%</b> and they are made of a header and contents."
            "All extra whitespace around the note templates will be removed. (if you need it use a backslash)</p>"
        "<p>The header is separated from the contents by either a space, <b>|</b> or newline."
            "This is the name to specify when using the note template.</p>"
        "<p>The body will be directly substituted into the text, but can contain arguments via a % and a number, e.g. <b>%1</b>."
            "See below for how they are used when using the template.</p>"
    "<h3>Using note templates</h3>"
        "<p>Note templates uses are surrounded with <b>%%</b>."
            "The arguments are separated by either a <b>|</b> or newline (but the first you can use a space for as well)</p>"
        "<p>The first thing is the name of the card to use, then the arguments to be substituted in order.</p>"
;

const QString PLUGVIEW_HELP = 
"<p>Select plugins to view information about them and disable them.</p>"
"<p>Plugin descriptions will only show for enabled plugins.</p>"
"<p>Press the <b>Load plugin</b> menu item to load one or more plugins from your hard drive."
    "This gives you the option to move them or to copy them (move gets rid of the original file, copy keeps the original).</p>"
"<h2>Status types</h2>"
    "<ul>"
        "<li>🤎 - the plugin is disabled</li>"
        "<li>💔 - the plugin failed to load</li>"
        "<li>💖 - the plugin loaded successfully!</li>"
    "</ul>"
;

const QString GAME_HELP =
"<p>Click on card to flip, and once flipped press a button as listed on the right to finish and reschedule the card.</p>"
"<p>Reset and Skip both don't change the score of the card but just reschedule it for later (skip a lot longer away than reset)</p>"
"<p>The times present are only a guideline. The app gives you cards sorted based on these times, so when you will recieve these cards is independent of the times.</p>"
"<p>Press &lt;Esc&gt; to go back to the home screen.</p>";
;

